/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TestesAutomatizados;

import io.restassured.RestAssured;
import io.restassured.http.ContentType;
import org.apache.http.HttpStatus;
import org.junit.BeforeClass;
import org.junit.Test;

import static io.restassured.RestAssured.*;
import static org.hamcrest.CoreMatchers.hasItem;
import static org.hamcrest.CoreMatchers.is;
import static org.junit.Assert.*;

public class AppTest {

    @BeforeClass
    public static void setup () {
        //Caso haja alguma falha o retorno será verboso com detalhes da situação.
        RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();
        //Caso haja diversos testes, não seria interessante ficar repetindo o endpoint completo
        baseURI = "https://7eb984w4j4.execute-api.us-east-1.amazonaws.com";
        basePath = "/dev";
    }

    @Test
    public void testeEnviaMensagem() {
        given().
            contentType(ContentType.JSON).
            body("{\"mensagem\": \"Mensagem de teste\", \"num_destinatario\": \"12345678901\"}").
        when().
                post("/lambdastresstest").
        then().
                statusCode(HttpStatus.SC_OK).
                body("statusCode", is(200)).
                body("body", is("\"Mensagem enviada com sucesso\""));
    }

    @Test
    public void testaCampoNumeroVazio() {
        given().
                contentType(ContentType.JSON).
                body("{\"mensagem\": \"Mensagem de teste\", \"num_destinatario\": \"\"}").
        when().
                post("/lambdastresstest").
        then().
                body("statusCode", is(400)).
                body("body", is("\"Numero inválido\""));
    }

    @Test
    public void testaCampoMensagemVazio() {
        given().
                contentType(ContentType.JSON).
                body("{\"mensagem\": \"\", \"num_destinatario\": \"12345678901\"}").
        when().
                post("/lambdastresstest").
        then().
                body("statusCode", is(200)).
                body("body", is("\"Mensagem enviada com sucesso\""));
    }

    @Test
    public void testeQtdDigitosNumeroDestinatario() {
        given().
                contentType(ContentType.JSON).
                body("{\"mensagem\": \"\", \"num_destinatario\": \"123456789011\"}").
        when().
                post("/lambdastresstest").
        then().
                body("statusCode", is(400)).
                body("body", is("\"Numero inválido\""));
    }
}
